<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="top_plate" params="name model:=pacs parent_link:=default_mount  height:=0.2 *origin">
    <!-- PACS Model -->
    <xacro:if value="${model == 'pacs'}">
      <!-- Variables -->
      <xacro:property name="plate_x_size" value="0.510"/>
      <xacro:property name="plate_y_size" value="0.430"/>
      <xacro:property name="plate_z_size" value="0.00635"/>

      <xacro:property name="post_radius" value="0.006"/>
      <xacro:property name="post_x_offset" value="0.040"/>
      <xacro:property name="post_y_offset" value="0.040"/>

      <!-- Spawn Top Plate -->
      <link name="${name}_link">
        <!-- Top Plate Mesh Visual -->
        <visual>
          <origin xyz="0 0 ${height}"/>
          <material name="clearpath_dark_grey" />
          <geometry>
            <mesh filename="package://clearpath_platform_description/meshes/dd100/attachments/pacs_top_plate.stl" />
          </geometry>
        </visual>
        <!-- Top Plate Box Collision -->
        <collision>
          <origin xyz="0 0 ${height + plate_z_size/2}"/>
          <material name="clearpath_dark_grey"/>
          <geometry>
            <box size="${plate_x_size} ${plate_y_size} ${plate_z_size}"/>
          </geometry>
        </collision>
        <!-- Quad Post Visual -->
        <visual>
          <origin xyz="${post_x_offset} ${post_y_offset} ${height/2}"/>
          <material name="clearpath_dark_grey"/>
          <geometry>
            <cylinder radius="${post_radius}" length="${height}"/>
          </geometry>
        </visual>
        <visual>
          <origin xyz="${post_x_offset} ${-post_y_offset} ${height/2}"/>
          <material name="clearpath_dark_grey"/>
          <geometry>
            <cylinder radius="${post_radius}" length="${height}"/>
          </geometry>
        </visual>
        <visual>
          <origin xyz="${-post_x_offset} ${post_y_offset} ${height/2}"/>
          <material name="clearpath_dark_grey"/>
          <geometry>
            <cylinder radius="${post_radius}" length="${height}"/>
          </geometry>
        </visual>
        <visual>
          <origin xyz="${-post_x_offset} ${-post_y_offset} ${height/2}"/>
          <material name="clearpath_dark_grey"/>
          <geometry>
            <cylinder radius="${post_radius}" length="${height}"/>
          </geometry>
        </visual>
        <!-- Quad Post Collision -->
        <collision>
          <origin xyz="0 0 ${height/2}"/>
          <material name="clearpath_dark_grey"/>
          <geometry>
            <box size="${2*post_x_offset + post_radius} ${2*post_y_offset} ${height}"/>
          </geometry>
        </collision>
      </link>

      <!-- Attach PACS Top Plate -->
      <joint name="${name}_joint" type="fixed">
        <child link="${name}_link"/>
        <parent link="${parent_link}"/>
        <xacro:insert_block name="origin"/>
      </joint>

      <!-- Generate PACS mounts -->
      <xacro:full_mounts
        name="${name}"
        parent_link="${name}_link"
        column="a"
        row="1"
        columns="5"
        rows="6"
        x="0.20"
        y="0.16"
        z="${height + plate_z_size}" />
      </xacro:if>

  </xacro:macro>
</robot>
