<?xml version="1.0"?>
<!--
Software License Agreement (BSD)

\file      common.urdf.xacro
\authors   Luis Camero <lcamero@clearpathrobotics.com>
           Roni Kreinin <rkreinin@clearpathrobotics.com>
\copyright Copyright (c) 2023, Clearpath Robotics, Inc., All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that
the following conditions are met:
 * Redistributions of source code must retain the above copyright notice, this list of conditions and the
   following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
   following disclaimer in the documentation and/or other materials provided with the distribution.
 * Neither the name of Clearpath Robotics nor the names of its contributors may be used to endorse or promote
   products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WAR-
RANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, IN-
DIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <material name="clearpath_dark_grey"><color rgba="0.2 0.2 0.2 1.0" /></material>
    <material name="clearpath_medium_grey"><color rgba="0.6 0.6 0.6 1.0" /></material>
    <material name="clearpath_light_grey"><color rgba="0.8 0.8 0.8 1.0" /></material>
    <material name="clearpath_yellow"><color rgba="0.8 0.8 0.0 1.0" /></material>
    <material name="clearpath_black"><color rgba="0.15 0.15 0.15 1.0" /></material>
    <material name="clearpath_white"><color rgba="1.0 1.0 1.0 1.0" /></material>
    <material name="clearpath_red"><color rgba="1.0 0.0 0.0 1.0" /></material>

    <material name="clearpath_aluminum">
      <color rgba="0.5 0.5 0.5 1"/>
    </material>
    <material name="clearpath_plastic">
      <color rgba="0.1 0.1 0.1   1"/>
    </material>

    <!--
        Standard Mount: adds link (w/o geometry) at given position
        - assumes orientation of parent
    -->
    <xacro:macro name="mount" params="name parent_link coordinate:=None *origin">
        <!-- Add Empty Mount -->
        <xacro:if value="${coordinate != None}">
          <link name="${name}_mount_${coordinate}"/>
          <joint name="${name}_mount_${coordinate}_joint" type="fixed">
            <child link="${name}_mount_${coordinate}"/>
            <parent link="${parent_link}"/>
            <xacro:insert_block name="origin"/>
          </joint>
        </xacro:if>
        <xacro:if value="${coordinate == None}">
          <link name="${name}_mount"/>
          <joint name="${name}_mount_joint" type="fixed">
            <child link="${name}_mount"/>
            <parent link="${parent_link}"/>
            <xacro:insert_block name="origin"/>
          </joint>
        </xacro:if>
    </xacro:macro>

    <!--
    Partial Riser Mounts: adds standard mounts for the specified row at the specified level
    - requires that base_mounts have been added
    - level (i.e. height) is w.r.t. the base level
    -->
    <xacro:macro name="row_mounts" params="name parent_link row column columns x:=0 y:=0 z:=0 spacing:=0.08  iteration:=0">
      <xacro:property name="chr" value="${dict(d97='a', d98='b', d99='c', d100='d', d101='e', d102='f', d103='g', d104='h')}" />
      <xacro:if value="${columns > iteration}">
        <xacro:property name="coordinate" value="${chr['d' + str(python.ord(column))] + python.str(row)}" />
        <xacro:mount
          name="${name}"
          parent_link="${parent_link}"
          coordinate="${coordinate}">
          <origin xyz="${x} ${y - spacing * iteration} ${z}"/>
        </xacro:mount>
        <xacro:row_mounts
          name="${name}"
          parent_link="${parent_link}"
          row="${row}"
          column="${chr['d' + str(python.ord(column) + 1)]}"
          columns="${columns}"
          spacing="${spacing}"
          x="${x}"
          y="${y}"
          z="${z}"
          iteration="${iteration + 1}" />
      </xacro:if>
    </xacro:macro>

    <xacro:macro name="full_mounts" params="name parent_link row column rows columns x:=0 y:=0 z spacing:=0.08 iteration:=0">
      <xacro:if value="${rows > iteration}">
        <xacro:row_mounts
          name="${name}"
          parent_link="${parent_link}"
          row="${row}"
          column="${column}"
          columns="${columns}"
          spacing="${spacing}"
          x="${x - spacing * iteration}"
          y="${y}"
          z="${z}" />
        <xacro:full_mounts
          name="${name}"
          parent_link="${parent_link}"
          row="${python.str(python.int(row) + 1)}"
          column="${column}"
          rows="${rows}"
          columns="${columns}"
          spacing="${spacing}"
          x="${x}"
          y="${y}"
          z="${z}"
          iteration="${iteration + 1}"/>
      </xacro:if>
    </xacro:macro>
</robot>
