<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="r100_rocker">

  <xacro:include filename="$(find clearpath_platform_description)/urdf/r100/wheels/wheel.urdf.xacro"/>

  <xacro:macro name="r100_rocker" params="prefix joint_type location *joint_limits">
    <link name="${prefix}_rocker_link">
      <visual>
        <origin xyz="0 0 0" rpy="${math.pi/2} 0 ${math.pi/2}" />
        <geometry>
          <mesh filename="package://clearpath_platform_description/meshes/r100/rocker.stl"/>
        </geometry>
        <material name="clearpath_black" />
      </visual>
      <inertial>
        <origin xyz="0 0 0" rpy="${math.pi/2} 0 ${math.pi/2}"/>
        <mass value="10.267"/>
        <inertia
          ixx="0.0288" ixy="2.20484e-6" ixz="-1.3145e-5"
          iyy="0.4324" iyz="1.8944e-3"
          izz="0.4130"/>
      </inertial>
    </link>

    <joint name="${prefix}_rocker" type="${joint_type}">
      <parent link="axle_link"/>
      <child link="${prefix}_rocker_link" />
      <origin xyz="${location*rocker_offset} 0 0" rpy="0 0 0" />
      <axis xyz="1 0 0" />
      <xacro:insert_block name="joint_limits" />
    </joint>

    <xacro:r100_wheel parent="${prefix}_rocker_link" prefix="${prefix}_left" side="${-location}">
      <origin xyz="0 ${rocker_width/2 + wheel_width/2} 0" rpy="0 0 0" />
    </xacro:r100_wheel>
    <xacro:r100_wheel parent="${prefix}_rocker_link" prefix="${prefix}_right" side="${location}">
      <origin xyz="0 ${-(rocker_width/2 + wheel_width/2)} 0" rpy="0 0 0" />
    </xacro:r100_wheel>

  </xacro:macro>
</robot>
